name: stardist-tf2.6
channels:
  - default
  - anaconda
  - nvidia
  - cpape
  - conda-forge
dependencies:
  - python=3.9
  - cudatoolkit=11.2.*
  - cudnn=8.1.*
  - nifty
  - elf # still one needs to download and use the latest version by adding to $PYTHONPATH
  - natsort
  - packaging
  - tqdm
  - pip
  - pip:
      - tensorflow==2.6.*
      - stardist
