data:
  path:
    - "/g/kreshuk/yu/Datasets/TMody2021Ovules/train/"
    - "/g/kreshuk/yu/Datasets/TMody2021Ovules/val"
  slice:
    patch_size: [96, 192, 192] # as large as possible
    stride_sizes: [48, 96, 96]
    filter_empty: True

tensorflow:
  threading:
    inter_op_parallelism_threads: 2
    intra_op_parallelism_threads: 16

axis_norm: [0, 1, 2]

stardist:
  model_dir: "/g/kreshuk/yu/Models/TMody2021Ovules"
  model_name: "20211130"
  n_rays: 96
  grid: [1, 2, 2]
  use_gpu: False
  n_channel_in: 1
  train_batch_size: 1
