data:
  path:
    - "/g/kreshuk/yu/Datasets/AVijayan2021Ovules/train/"
    - "/g/kreshuk/yu/Datasets/AVijayan2021Ovules/val"
  slice:
    patch_size: [ 96, 192, 192 ]  # as large as possible
    stride_sizes: [ 48, 96, 96 ]
    filter_empty: True

tensorflow:
  threading:
    inter_op_parallelism_threads: 2
    intra_op_parallelism_threads: 16

axis_norm: [ 0, 1, 2 ]

stardist:
  model_dir: "/g/kreshuk/yu/ovule-nuclei-segmentation/models"
  model_name: "athul"
  n_rays: 96
  grid: [ 2, 4, 4 ]
  use_gpu: False
  n_channel_in: 1
  train_batch_size: 1
